repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.9.7
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: 3.7.9
#    hooks:
#    - id: flake8
