color_mode: {{cookiecutter.color_mode}}
deterministic: true
mean_img: nan
model_name: model_name
n_classes: {{cookiecutter.n_classes}}
random_seed: 9854321
save_format: png
segmentation: true
std_img: nan
target_size: {{cookiecutter.target_size}}
test: true
train_model:
  batch_size: 1
  callbacks:
    callbacks:
    - ReduceLROnPlateau
    mode: auto
    monitor: val_loss
  epochs: 50
train_test_split:
  n_split: 10
  shuffle: true
