target_size: {{cookiecutter.target_size}}
n_classes:  {{cookiecutter.n_classes}}
color_mode: {{cookiecutter.color_mode}}
train_model:
  batch_size: 32
  epochs: 10
mean_img:
  g: nan
random_seed: 12345
train_test_split:
  n_split: 10
  shuffle: true
